import Image from "next/image";
import Link from "next/link";
import { BookingBar } from "@/components/BookingBar";
import { RoomCard } from "@/components/RoomCard";
import { hotel, rooms } from "@/lib/data";

export default function Home() { return <>
  <section className="hero"><Image src="/images/faulkton-inn-exterior.jpg" alt="Exterior of Faulkton Inn at 700 Main Street" fill priority sizes="100vw" /><div className="hero-shade"></div><div className="hero-copy shell"><p className="eyebrow light">Family-run hospitality in Faulkton, South Dakota</p><h1>Stay in the heart<br />of Faulkton.</h1><p>Comfortable rooms, a warm welcome, and an easy place to settle in at 700 Main Street.</p><div className="actions"><Link className="button button-cream" href="/booking">Check availability</Link><a className="button button-ghost" href={hotel.phoneHref}>Call the inn</a></div></div><p className="photo-credit">Photo: Faulkton Area Economic Development</p></section>
  <div className="booking-wrap shell"><BookingBar /></div>
  <section className="trust-strip"><div className="shell trust-grid"><div><b>Family-run</b><span>Personal, hands-on hospitality</span></div><div><b>Main Street</b><span>Near the heart of town</span></div><div><b>Easy arrival</b><span>Free self-parking listed</span></div><div><b>Stay connected</b><span>Free Wi-Fi listed</span></div></div></section>
  <section className="section shell"><div className="section-head"><div><p className="eyebrow">Rest easy</p><h2>Room for the way<br />you travel.</h2></div><div><p>From a practical queen room to extra space for a family or group, find a layout that fits your stay.</p><Link className="text-link" href="/rooms">Explore all rooms <span>↗</span></Link></div></div><div className="room-grid">{rooms.slice(0, 3).map((room, i) => <RoomCard room={room} index={i} key={room.slug} />)}</div></section>
  <section className="story-section"><div className="story-card shell"><div className="story-mark"><span>F</span><i></i></div><div><p className="eyebrow">A welcome with a name</p><h2>Family-run.<br />Faulkton proud.</h2><p>Rebekah and José Epp bring a hands-on approach to the inn, caring for the property and the people who stay here. Whether you’re in town to see family, attend a local event, work nearby, or simply need a comfortable stop along the way, the welcome is personal.</p><Link className="text-link light-link" href="/about">Meet your hosts <span>↗</span></Link></div></div></section>
  <section className="section shell amenities-home"><div><p className="eyebrow">Simple comforts</p><h2>The essentials,<br />thoughtfully kept.</h2></div><div className="amenity-list"><div><span>01</span><h3>Free Wi-Fi</h3><p>Stay connected during your visit.</p></div><div><span>02</span><h3>Free parking</h3><p>Convenient on-site self-parking.</p></div><div><span>03</span><h3>EV charging</h3><p>A charger is available on site.</p></div><div><span>04</span><h3>Outdoor grill</h3><p>A relaxed place to gather outside.</p></div></div></section>
  <section className="local-feature"><div className="local-graphic"><span className="sun"></span><span className="horizon"></span><span className="carousel">CAROUSEL<br />CITY</span></div><div className="local-copy"><p className="eyebrow light">Beyond your room</p><h2>Discover the<br />Carousel City.</h2><p>Step outside the inn and explore Faulkton’s small-town character, from local history and public art to parks and the community’s landmark carousel.</p><Link className="button button-cream" href="/faulkton">Explore Faulkton</Link></div></section>
  <section className="contact-band shell"><div><p className="eyebrow">Find your way here</p><h2>Right on Main Street.</h2><p>{hotel.address}</p></div><div className="contact-actions"><a className="button" href={hotel.mapsUrl} target="_blank" rel="noreferrer">Get directions</a><a className="text-link" href={hotel.phoneHref}>{hotel.phone}</a></div></section>
  <section className="final-cta"><p className="eyebrow light">Your room is waiting</p><h2>Ready to settle in?</h2><p>Check current availability online, or give us a call.</p><div className="actions"><Link className="button button-cream" href="/booking">Check availability</Link><a className="button button-ghost" href={hotel.phoneHref}>Call {hotel.phone}</a></div></section>
</>; }
