"use client";
import { FormEvent, useState } from "react";
import { hotel } from "@/lib/data";
function iso(offset: number) { const d = new Date(); d.setDate(d.getDate() + offset); return d.toISOString().slice(0, 10); }
export function BookingBar({ compact = false }: { compact?: boolean }) {
  const [error, setError] = useState("");
  const [childCount, setChildCount] = useState(0);
  function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const data = new FormData(e.currentTarget); const checkIn = String(data.get("checkIn")); const checkOut = String(data.get("checkOut")); const adults = Number(data.get("adults")); const children = Number(data.get("children")); const childAges = Array.from({length: children},(_,i)=>Number(data.get(`childAge${i+1}`))); if (!checkIn || !checkOut || checkOut <= checkIn) { setError("Choose a checkout date after your check-in date."); return; } if (adults < 1 || adults > 14 || children < 0 || children > 6 || childAges.some(age=>age<0||age>17)) { setError("Check the guest count and each child’s age."); return; } setError(""); const intent = { checkIn, checkOut, adults, children, childAges, rooms: 1 }; sessionStorage.setItem("faulkton-booking-intent", JSON.stringify(intent)); const query = new URLSearchParams({ NumRoom: "1", "NumAdult-Room1": String(adults), "NumChild-Room1": String(children) }); childAges.forEach((age,i)=>query.set(`Room1-Child${i+1}Age`,String(age))); const url = `https://www.expedia.com/go/hotel/info/${hotel.expediaPropertyId}/${checkIn}/${checkOut}?${query.toString()}`; window.location.assign(url); }
  return <form className={`booking-bar ${compact ? "booking-compact" : ""}`} onSubmit={submit}><label><span>Check in</span><input name="checkIn" type="date" defaultValue={iso(7)} min={iso(0)} required /></label><label><span>Check out</span><input name="checkOut" type="date" defaultValue={iso(8)} min={iso(1)} required /></label><label><span>Adults</span><select name="adults" defaultValue="2"><option value="1">1 adult</option><option value="2">2 adults</option><option value="3">3 adults</option><option value="4">4 adults</option><option value="5">5 adults</option><option value="6">6 adults</option></select></label><label><span>Children</span><select name="children" value={childCount} onChange={e=>setChildCount(Number(e.target.value))}><option value="0">No children</option><option value="1">1 child</option><option value="2">2 children</option><option value="3">3 children</option><option value="4">4 children</option></select></label><button className="button" type="submit">Check availability <span aria-hidden="true">→</span></button>{childCount>0&&<div className="child-ages"><span>Children’s ages</span>{Array.from({length:childCount},(_,i)=><label key={i}><span>Child {i+1}</span><select name={`childAge${i+1}`} defaultValue="8" aria-label={`Child ${i+1} age`}>{Array.from({length:18},(_,age)=><option key={age} value={age}>{age}</option>)}</select></label>)}</div>}{error && <p className="form-error" role="alert">{error}</p>}</form>;
}
