import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Image from "next/image";
import { CallPrompt } from "@/components/CallPrompt";
import { hotel } from "@/lib/data";
import { rooms } from "@/lib/data";
export function generateStaticParams(){return rooms.map(({slug})=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const room=rooms.find(r=>r.slug===slug);return room?{title:room.shortName,description:room.summary}:{} }
export default async function RoomPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const room=rooms.find(r=>r.slug===slug);if(!room)notFound();return <section className="room-detail shell"><p className="eyebrow">Rooms / {room.shortName}</p><h1>{room.shortName}</h1><div className="room-detail-grid"><div><div className="room-detail-hero"><Image src={room.image} alt={room.imageAlt} fill priority sizes="70vw"/></div><div className="room-detail-gallery"><div><Image src="/images/inn-room.jpg" alt="In-room work area and lounge chair at Faulkton Inn" fill sizes="35vw"/></div><div><Image src="/images/inn-bathroom.jpg" alt="Guest bathroom at Faulkton Inn" fill sizes="35vw"/></div></div><div className="prose room-copy"><p className="eyebrow">Your stay</p><h2>A comfortable place to land.</h2><p>{room.summary} Call the inn to confirm the best available room for your dates and party.</p><h3>Good to know</h3><p>Free Wi-Fi and self-parking are available property-wide. Please call for current room details, rates, and accessibility information.</p></div></div><aside className="room-facts"><p className="eyebrow">At a glance</p><dl><div><dt>Sleeps</dt><dd>Up to {room.occupancy}</dd></div><div><dt>Beds</dt><dd>{room.beds}</dd></div><div><dt>Current rate</dt><dd>Call the inn</dd></div><div><dt>Reservations</dt><dd>By phone</dd></div></dl><CallPrompt label="Call for availability" className="button" /><a className="room-phone" href={hotel.phoneHref}>{hotel.phone}</a></aside></div></section>}
